# This is an R script for differential gene expression analysis using the DESeq2 tool (Love et al., 2014)
#--------------------------------------------------------------------------------------------------------
# install packages if needed
# BiocManager::install("GenomicFeatures")
# BiocManager::install("txdbmaker")
# BiocManager::install('biomaRt')
# BiocManager::install("pathview")

# Load required libraries
library(DESeq2)
library(tidyverse)
library(dplyr)
library(EnhancedVolcano)
library(pheatmap)
library(apeglm)
library(RColorBrewer)
library(ggplot2)
library(openxlsx)

# Set your working directory
setwd('choose/your/path')

# Read Metadata file containing the sample information
metadata <- read.delim("metadata.txt")

# Import the gene raw counts generated by featureCounts (see 4.featureCounts.sh file)
counts <- read.table("mod_countsFV.txt", header = TRUE, row.names = 1)
rownames(counts) <- sub("^gene:", "", rownames(counts)) # remove prefixes if needed. Substitute the ^gene: with whatever the prefix is.

# Check if the metadata rownames are the same as the counts table column names
metadata_samples <- metadata$Sample_Name
all(metadata_samples == colnames(counts))
rm(metadata_samples) #after checking, remove the metadata_samples

# Indicate the desired factor (Condition, time_point, etc) and generate the DESeq object.
metadata$Condition <- factor(metadata$your_factor) #change the factor to your desire (for example "Condition")
dds = DESeqDataSetFromMatrix(countData =  counts, 
                             colData =  metadata, 
                             design = ~ your_factor) #Construct the DESeq object.

# Pre-filter lowly expressed genes. Here, we determine the lowest number of observations in all samples as 10, present in at least three samples.
keep <- rowSums(counts(dds) >= 10) >= 3
dds <- dds[keep,]

#---------------------------------------------------------------------------------------------------
# Quality control and exploratory data analysis
# Principal Component Analysis (PCA) - PCA helps to understand the structure and the variability of your data and if your samples are grouped as expected
vsdata <- vst(dds, blind = TRUE) # Estimate dispersion and apply a variance stabilizing transformation
# using the DESEQ2 plotPCA fxn we can do a principal component analysis
plotPCA(vsdata, intgroup = 'your_factor')+
  ggtitle("Principal Component Analysis")+
  geom_point(size = 6) 

#Check sample distances and create a heatmap to check sample correlations
sampleDists <- dist(t(assay(vsdata)))
pheatmap(
  as.matrix(sampleDists),
  clustering_distance_rows = sampleDists,
  clustering_distance_cols = sampleDists
)

# Determine your reference group to compare your samples against. It could be Mock, Healthy or anything depending on your metadata
dds$your_factor <- relevel(dds$your_factor, ref = "your_reference")

# Run the deferential expression analysis using DESeq
dds <- DESeq(dds, minReplicatesForReplace = Inf)
resultsNames(dds)
res <- results(dds, contrast = c("your_factor", "treatment1", "your_reference")) # Change the treatment group to be compared with the reference group according to your desire
summary(res)

# Remove NAs and then sort summary list by the false discovery rate (FDR) adjusted p-value 
res <- res[!is.na(res$padj), ]
res <- res[order(res$padj), ]
head(res)

# Shrink data to reduce the noise from the lowly-expressed genes and create a diagnostic MA plot
resLFC <- lfcShrink(
  dds,
  coef = "your_factor_treatment1_vs_your_reference",
  type = "apeglm",
) # This command shrinks the noisy gene expression data, and it is useful if you have low number of samples or lowly expressed genes

summary(resLFC) # Check the differences with the summary(res)

#Create the MA plot
pdf('choose/your/path/MA Plot.pdf', #open the pdf device to create a high-quality publication plot
    width = 7,
    height = 5)

plotMA(resLFC, ylim = c(-5, 5), main = "MA Plot")

dev.off() # Close the devise and save your pdf file with the plot

#Create a data frame to extract the results from the results object, with shrunk data
res_df <- as.data.frame(resLFC)

#Add a column to determine if a gene is up- or down- regulated if the fold change is above or below 1. 
#Start with p-adj = 0.05 as your cutoff and then you can play with the settings
res_df <- res_df %>%
  mutate(Significance = case_when(
    log2FoldChange >=1 & padj <= 0.05 ~ 'Upregulated',
    log2FoldChange <=-1 & padj <= 0.05 ~ 'Downregulated',
    abs(log2FoldChange) < 1 | padj > 0.05 ~ 'Not significant'
  ))

res_df <- res_df[!is.na(res_df$padj), ] #remove NAs

# Reorder the table so that the smallest FDR adjusted p-value is on the top of the data frame
res_df=res_df[order(res_df$padj),]

# Save the table as an xlsx file
write.xlsx(res_df, 'choose/your/path/your_excel_file.xlsx', colNames=TRUE, rowNames=TRUE)

#-------------------------------------------------------------------------------------------
# Continue with the exploratory analysis
top_genes <- res_df %>%
  filter(padj <= 0.05, abs(log2FoldChange) >= 1) %>%
  arrange(padj) %>%
  head(10)

# Create the volcano plot to check patterns on gene expression
pdf('choose/your/path/Volcano plot.pdf',
    width = 7,
    height = 5)

ggplot(data=res_df, 
       aes(x=log2FoldChange, y=-log10(padj), color = Significance)) + 
  geom_point() + 
  geom_vline(xintercept=c(-1, 1), col="red", linetype = 'dashed') + # here you can change the log fold change to your desire
  geom_hline(yintercept=-log10(0.05), col="red", linetype = 'dashed') + # here you can change the adjusted p-value to your desire
  theme_gray()+
  geom_text_repel(
    data = top_genes,
    aes(label = rownames(top_genes)), # you annotate the code of your top expressed genes into the plot
    color = 'black'
  ) +
  labs(x = 'LogFC', y = '-Log10(FDR)') + 
  scale_color_manual(values = c('blue','grey70','red'))+ #blue for down-regulation, grey for not-significant and red for the up-regulation
  labs(
    title = 'your title',
    subtitle = 'Log2FC cutoff = 1; Adjusted p-value cutoff = 0.05' # Change the subtitle according to your desire
  )+ theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.subtitle = element_text(size = 11, face = "italic")
  )

dev.off() # Close the devise and save the pdf with your plot
#-----------------------------------------------------------------------------------------------------------------------

# Functional enrichment analysis
# If not installed, install biomart package

# BiocManager::install("biomaRt")
# Load the library
library('biomaRt')

# Create the mart object
mart <- useEnsemblGenomes(
  biomart = "plants_mart",
  dataset = "vvinifera_eg_gene", # Choose the desired genome, for example here we use the Vitis vinifera dataset
  host = "https://plants.ensembl.org"
)

listDatasets(mart) # You can list the available datasets with this fxn

attributes <- listAttributes(mart) # This lists the attributes that you may need to annotate your genes

# Search for annotation based on ensembl_gene_id identifiers
annot <- getBM(filters= "ensembl_gene_id", # Which identifier you are using
               attributes= c("ensembl_gene_id", 
                             "description", 
                             "start_position", 
                             "end_position", 
                             "strand", 
                             "external_gene_name",
                             "name_1006",
                             "go_id"), # Which attributes you want to collect
               values=rownames(res_df), # The code names of your genes
               mart= mart) # The mart you previously defined 

# Save an RDS file
# Some times the server is down, so you save the RDS in order to be able to work offline
saveRDS(annot, "Zm_annotation_full.rds")
annot <- readRDS("Zm_annotation_full.rds") # Read the RDS file

# Join the results table with the annotations
res_df$ensembl_gene_id <- rownames(res_df)

res_df_annot<- res_df %>%
  left_join(annot, by = 'ensembl_gene_id')

#Save the data as an xlsx file
write.xlsx(res_df_annot, file="choose/your/path/Annotated table for DEGs.xlsx", colNames=TRUE, rowNames=TRUE)

#------------------------------------------------------------------------------------------------------------
# Let's start now with the annotation of our genes. In not installed, install clusterProfiler package
#BiocManager::install("clusterProfiler")
# Load the clusterProfiler library
library(clusterProfiler)

## Start with the clusterProfiler package for gene ontology (GO) analysis
go_map <- getBM(filters= "ensembl_gene_id",
  attributes = c(
    "ensembl_gene_id",
    "go_id",
    "name_1006",
    "namespace_1003"),
  mart = mart,
  values=rownames(res_df)
)

go_map <- go_map[!is.na(go_map$go_id), ] #remove NAs

# Create the dataframes with the GO IDs and the GO names
TERM2GENE <- go_map[, c("go_id", "ensembl_gene_id")]
TERM2NAME <- unique(go_map[, c("go_id", "name_1006")])

# Filter only for the significant genes
background_genes <- rownames(res_df) # It is very important to have your the background genes, which are critical for the statistical context
sig_genes <- rownames(res_df)[res_df$padj < 0.05] # Change the adjusted p-value to your desire

# Create the enrichment object
ego <- enricher(
  gene = sig_genes,
  TERM2GENE = TERM2GENE,
  TERM2NAME = TERM2NAME,
  universe = background_genes,
  pAdjustMethod = "BH",
  minGSSize = 10,
  maxGSSize = 500
)

# Add ontology (namespace_1003) to the enrichment results
ego@result <- merge(
  ego@result,
  unique(go_map[, c("go_id", "namespace_1003")]),
  by.x = "ID",
  by.y = "go_id",
  all.x = TRUE
)

# Add 
ego@result$Ontology <- dplyr::recode(
  ego@result$namespace_1003,
  "biological_process" = "Biological_Process",
  "molecular_function" = "Molecular_Function",
  "cellular_component" = "Cellular_Component"
)

ego@result$Description <- stringr::str_wrap(ego@result$Description, width = 100)

# Save the plot
pdf('choose/your/path/Dotplot.pdf',
    width = 10,
    height = 7)

dotplot(ego, color = "p.adjust",
        showCategory = 30,
        label_format = 100)+
  aes(x = FoldEnrichment,
      y = Description)+
  labs(
    x = "Fold Enrichment",
    y = "GO Term Description")+
  ggtitle('GO Enrichment')+
  geom_point(
    aes(
      size = Count,
      fill = p.adjust,
      color = Ontology
    ),
    shape = 21, stroke = 1.2
  ) +
  scale_color_manual(
    values = c(
      Biological_Process = "black",
      Molecular_Function = "darkgreen",
      Cellular_Component = "darkblue"
    ))+
  theme(
    plot.title = element_text(size = 14, face = "bold"))

dev.off() # Turn off the device

#----------------------------------------------------------
# Begin with  KEGG analysis
id_map <- getBM(
  attributes = c("ensembl_gene_id", "entrezgene_id"),
  filters = "ensembl_gene_id",
  mart = mart,
  values = sig_genes
)

# Keep only valid Entrez IDs
id_map <- id_map[!is.na(id_map$entrezgene_id), ]
entrez_sig <- unique(id_map$entrezgene_id)

# Conduct KEGG analysis
ekegg <- enrichKEGG(
  gene         = entrez_sig,
  organism     = "zma", #vvi
  pvalueCutoff = 0.05,
  qvalueCutoff = 0.05
)

# Save the barplot or dotplot with the significant pathways
pdf('choose/your/path/Barplot_KEGG.pdf',
    width = 10,
    height = 7)

barplot(ekegg, x = "Count", showCategory = 20)+
  ggtitle('your title') +
  labs(
    x = "Count",
    y = "KEGG Pathway")+
  theme(
    plot.title = element_text(size = 14, face = "bold"))
  
dev.off() #Turn off the device

cnetplot(ekegg, showCategory = 20) # Ccheck the network if you want

# Visualize the pathway of your interest
library(pathview) #Load the pathview library

pathway_id <- "your pathway id" # Change that in order to visualize your desired pathway
species <- "your species"

fc <- res_df$log2FoldChange

# Map Ensembl IDs to Entrez IDs
names(fc) <- id_map$entrezgene_id[match(rownames(res_df), id_map$ensembl_gene_id)]

# Remove NAs
fc <- fc[!is.na(names(fc))]

#create the pathway
pathview(
  gene.data  = fc,
  pathway.id = pathway_id,
  species    = species,
  out.suffix = "Biosynthesis of amino acids_all_genes",
  limit      = list(gene = max(abs(fc)))  # optional: scales colors to full range
)

#---------------------------------------------------------------------------
# Check how individual genes are expressed in the different treatments
df <- plotCounts(dds,
                 gene = 'your gene', # Change the gene id to your desire
                 intgroup = "Condition",
                 returnData = TRUE)

ggplot(df, aes(x = Condition, y = count)) +
  geom_point(size = 5) +
  stat_summary(fun = mean, geom = "point", color = "red", size = 3) +
  theme_bw() +
  labs(title = 'your title', y = "Normalized counts")

sessionInfo() # Extract the information about the packages used in this session